# Generated by Django 2.2.11 on 2020-04-02 09:26

from django.db import migrations, models
import djongo.models.fields
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('classname', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('weapon', models.CharField(max_length=15)),
                ('rarity', models.CharField(max_length=1)),
                ('availability', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=5)),
                ('Str', models.CharField(max_length=5)),
                ('total_max_hp', models.CharField(blank=True, max_length=5, null=True)),
                ('total_max_str', models.CharField(blank=True, max_length=5, null=True)),
                ('base_min_might', models.CharField(blank=True, max_length=6, null=True)),
                ('base_max_might', models.CharField(blank=True, max_length=6, null=True)),
                ('defense', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=15, null=True)),
                ('obtained_form', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=my_app.models.upload_location, width_field='width_field')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=my_app.models.upload_location, width_field='width_field')),
                ('url', models.URLField()),
                ('skill_1', djongo.models.fields.ArrayField(model_container=my_app.models.Skill)),
                ('skill_2', djongo.models.fields.ArrayField(model_container=my_app.models.Skill)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('remark2', models.CharField(blank=True, max_length=255, null=True)),
                ('remark3', models.CharField(blank=True, max_length=255, null=True)),
                ('remark4', models.CharField(blank=True, max_length=255, null=True)),
                ('remark5', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=my_app.models.upload_location, width_field='width_field')),
                ('level_1', models.CharField(max_length=255)),
                ('level_2', models.CharField(max_length=255)),
                ('level_3', models.CharField(max_length=255)),
            ],
        ),
    ]
