# Generated by Django 2.2.11 on 2020-04-06 10:30

from django.db import migrations, models
import django.db.models.deletion
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_icon)),
                ('icon_url', models.URLField()),
                ('level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('level_4', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdventurerAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_icon)),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_icon)),
                ('icon_url', models.URLField()),
                ('level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('level_4', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('class_name', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('weapon', models.CharField(max_length=15)),
                ('rarity', models.CharField(max_length=1)),
                ('availability', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=5)),
                ('Str', models.CharField(max_length=5)),
                ('total_max_hp', models.CharField(blank=True, max_length=5, null=True)),
                ('total_max_str', models.CharField(blank=True, max_length=5, null=True)),
                ('base_min_might', models.CharField(blank=True, max_length=6, null=True)),
                ('base_max_might', models.CharField(blank=True, max_length=6, null=True)),
                ('defense', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=15, null=True)),
                ('obtained_form', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_icon)),
                ('icon_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_image)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('remark2', models.CharField(blank=True, max_length=255, null=True)),
                ('remark3', models.CharField(blank=True, max_length=255, null=True)),
                ('remark4', models.CharField(blank=True, max_length=255, null=True)),
                ('remark5', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('skill_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dragon_skill_1', to='my_app.Skill')),
                ('skill_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dragon_skill_2', to='my_app.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('weapon', models.CharField(max_length=15)),
                ('rarity', models.CharField(max_length=1)),
                ('availability', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=5)),
                ('Str', models.CharField(max_length=5)),
                ('total_max_hp', models.CharField(blank=True, max_length=5, null=True)),
                ('total_max_str', models.CharField(blank=True, max_length=5, null=True)),
                ('base_min_might', models.CharField(blank=True, max_length=6, null=True)),
                ('base_max_might', models.CharField(blank=True, max_length=6, null=True)),
                ('defense', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=15, null=True)),
                ('obtained_form', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_icon)),
                ('icon_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_image)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('remark2', models.CharField(blank=True, max_length=255, null=True)),
                ('remark3', models.CharField(blank=True, max_length=255, null=True)),
                ('remark4', models.CharField(blank=True, max_length=255, null=True)),
                ('remark5', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('ability_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_1', to='my_app.AdventurerAbility')),
                ('ability_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_2', to='my_app.AdventurerAbility')),
                ('ability_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_3', to='my_app.AdventurerAbility')),
                ('chain_co_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chain_co_ability', to='my_app.AdventurerAbility')),
                ('co_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_ability', to='my_app.AdventurerAbility')),
                ('skill_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_1', to='my_app.Skill')),
                ('skill_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_2', to='my_app.Skill')),
            ],
        ),
    ]
