# Generated by Django 2.2.11 on 2020-04-07 09:36

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=my_app.models.upload_image)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
