# Generated by Django 2.2.11 on 2020-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventurer',
            old_name='classname',
            new_name='class_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='level_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
